### ISSUE TITLE
feat: Improve search on mentor page

### ISSUE THREAD

**Issue by Neha** [WomenWhoCode/london#116]
As of now, the search's UX is not great. We should implement the following changes to improve it

1. Add a search button
2. Keyword search should take place on keypress
3. Should show the count of search result
4. Add loader while search is going on
5. Mentor images should be mapped by the Index https://wwcodelondon.slack.com/archives/C046TG3MHJR/p1688843216863139

**Comment by nora-weisser** [comment]
Proposed search section design:
![Screenshot 2023-07-19 at 19 52 12](https://github.com/WomenWhoCode/london/assets/65826199/09b5b7e4-7e92-4685-9970-b2d3b38efe2c)
It would be also nice to make advanced filters section hide/show. On click of the advanced filters, the rest of the filters will be available.

**Comment by khairahscorner** [comment]
Can the members of the study group get access to this Figma design? @nora-weisser
