### ISSUE TITLE
feat: Enable registration based on mentors availability

### ISSUE THREAD

**Issue by nora-weisser** [WomenWhoCode/london#129]
Currently, we initiate mentee registration for ad-hoc sessions on a monthly basis, enabling them to apply for mentors. Given that mentors may have availability in specific months, it would be more flexible to establish a structured timetable. This would involve reaching out to mentors beforehand to ascertain their upcoming availability.

Technical details:
Additional fields in yml should look like (we can put only two months for now and later extend):
```
availability: [5, 6, 7, 8] 
```

Logic is following:
Button should be enabled the first 7 days of the month and disabled after that.

**Comment by dricazenck** [comment]
Resolved by this #316
