### ISSUE TITLE
feat: Add "Join our slack community" 

### ISSUE THREAD

**Issue by dricazenck** [WomenWhoCode/london#145]
Include [this link](https://join.slack.com/t/wwcodelondon/shared_invite/zt-1kltyfn5s-vCzO9oALyOJP5m11P4fOLg) for our slack group in the footer as part of our social medidas. 

![image](https://github.com/WomenWhoCode/london/assets/3664747/1a68d48b-62d3-4515-acdc-844aaa0573c4)

**Comment by khairahscorner** [comment]
I made a PR for #134 but since this is similar, is it fine to add an extra commit to include this feature or a separate PR should be created? @dricazenck

**Comment by dricazenck** [comment]
It is up to you, you could close both in the same PR no problem because they are smaller. But considering it is already merged, I guess it has to be another one 🙈
