### ISSUE TITLE
feat: Show Mentors hours per month

### ISSUE THREAD

**Issue by dricazenck** [WomenWhoCode/london#150]
Include in the mentors card the total of hours available per month for mentoring. 

* In the Mentor data has already hours per month 
* In case the hour is zero, it should not show the availability.

**Comment by khairahscorner** [comment]
@dricazenck are the values currently included for `hours` in the `mentors.yml` file per week or month?

**Comment by dricazenck** [comment]
@khairahscorner, It is hours per month.
