### ISSUE TITLE
bug: Contribution guidelines, open an issue link to be updated

### ISSUE THREAD

**Issue by Neha** [WomenWhoCode/london#155]
### Describe the bug
1. As of now, in the contribution guideline "open an issue" link is redirecting to the issues page

### To Reproduce
1. Go to ['...'](https://github.com/WomenWhoCode/london/blob/67394993ed51b038a0c8acb401e4305552296b55/CONTRIBUTING.md#reporting-issues-or-suggesting-changesfeatures-to-the-existing-repo)
2. Click on "open an issue"
3. It will take you to the issues page

### Expected behavior
We should update the link so that it will go to: https://github.com/WomenWhoCode/london/issues/new/choose

### Screenshots
NA

### Reproducibility
- [ ] The bug is reproducible consistently.
- [ ] The bug is sporadic or occurs randomly.

### Impact
- [ ] The bug affects critical functionality.
- [ ] The bug affects minor functionality.
- [ ] The bug is a cosmetic issue.

### Related Issues/PRs
If you know of any related issues or pull requests, link them here.

### Proposed Solution (optional)
If you have any ideas on how to fix the bug or potential areas to investigate, suggest them here.

### Your Contribution (optional)
If you're able and willing to contribute a fix, mention it here.

**Comment by khairahscorner** [comment]
Will address this in #153
