### ISSUE TITLE
bug: Link to the video for the two first events redirects to the same video link

### ISSUE THREAD

**Issue by nora-weisser** [WomenWhoCode/london#157]
### Describe the bug

Link to the video for the two first events redirects to the same video link.

### To Reproduce
1. Open the link: https://womenwhocode.github.io/london/resources
2. Navigate to the Events Section
3. Click on the youtube icon for the two first events
![same_link_issue](https://github.com/WomenWhoCode/london/assets/65826199/dffb6a6b-d8d1-491a-adfa-589fff864144)

### Actual behavior

Two links redirect to the same video: https://www.youtube.com/watch?v=AuDyfjDr9rA

### Expected behavior
What makes a good mentor? Panel Discussion - https://www.youtube.com/watch?v=AuDyfjDr9rA
How to get the most out of Mentorship Programme? Panel Discussion - https://www.youtube.com/watch?v=mznVrMbcFxk

### Desktop (please complete the following information):
 - Browser Chrome

### Reproducibility
- [x] The bug is reproducible consistently.
- [ ] The bug is sporadic or occurs randomly.

### Impact
- [ ] The bug affects critical functionality.
- [x] The bug affects minor functionality.
- [ ] The bug is a cosmetic issue.

**Comment by Oli0li** [comment]
Hello! May I work on this please?
