### ISSUE TITLE
bug: JS error in console related to navbar

### ISSUE THREAD

**Issue by dricazenck** [WomenWhoCode/london#160]
### Describe the bug
There is an issue on JS related to menu trying to add class into undefined object. 

### To Reproduce
1. Go to the website
2. open inspect the code 
3. check console log
4. See error `navbar.js:23 Uncaught TypeError: Cannot read properties of undefined (reading 'addClass')`

### Expected behavior
No exception should be trigger on console while navigating into our website

### Screenshots
![image](https://github.com/WomenWhoCode/london/assets/3664747/5f2fab1f-4819-4a55-921e-be7217be31c0)

### Reproducibility
- [x] The bug is reproducible consistently.

### Impact
- It is blocking test automation

**Comment by Neha** [comment]
@dricazenck I am not able to see the error in the console.

**Comment by dricazenck** [comment]
Sorry, @Neha I fixed that already, I was thinking the issue would be closed. You can see [here](fix: navbar exception #162)https://github.com/WomenWhoCode/london/pull/162 

But I am closing now.
