### ISSUE TITLE
QA Automation: Reorganise data checks

### ISSUE THREAD

**Issue by vamelchenia** [WomenWhoCode/london#193]
### Is your feature request related to a problem? Please describe.
Currently, data is verified by manually copying a data file to `cypress/fixtures/test_data` and comparing with the respective data file in `_data` folder in the root repo directory. This is ok but requires to maintain two copies of data file. 

### Describe the solution you'd like
In this task, it is proposed to add a `before` hook where before running tests data file will be copied to `cypress/fixtures/test_data` and then verify data looping through each UI element (visibility is ok, links are opening, texts verifications etc.)
Update all tests that verify data to a new approach.

**Comment by dricazenck** [comment]
Amazing, that would be really great.

**Comment by vamelchenia** [comment]
https://github.com/WomenWhoCode/london/pull/200
