### ISSUE TITLE
fix: Limit mentors area to the same size

### ISSUE THREAD

**Issue by dricazenck** [WomenWhoCode/london#35]
In order to make the mentor's page with the same space between mentors, it is necessary to implement the following:

* limit the mentor's bio area to a specific size (css `width`)
* add a button to "read more" which will show the complete bio information. 
* and the `Show less` button to hide the information 
* only shows the buttons to hide and show the details of the bio text that has more than a limited `characters` number for example. But any other logic can be applied.

**Comment by Neha** [comment]
Hey, can I take this issue?

**Comment by nora-weisser** [comment]
@Neha , sure!

**Comment by Neha** [comment]
PR: https://github.com/WomenWhoCode/london/pull/120

**Comment by dricazenck** [comment]
Solved
