### ISSUE TITLE
feat: Re-organize Menu and Sub-menu

### ISSUE THREAD

**Issue by dricazenck** [WomenWhoCode/london#55]
1. [HOME](https://womenwhocode.github.io/london)
2. [MENTORS](https://womenwhocode.github.io/london/mentors)
3. [RESOURCES](https://womenwhocode.github.io/london/resources)
4. HOW IT WORKS (no page, it is just to group the links)
  4.1 [LONG-TERM RELATIONSHIPS TIMELINE](https://womenwhocode.github.io/london/timeline.html)
  4.2 [AD-HOC MENTORSHIP TIMELINE](https://womenwhocode.github.io/london/adhoc-timeline.html)
  4.3. [CODE OF CONDUCT](https://womenwhocode.github.io/london/code-of-conduct)
  4.4. [FAQ](https://womenwhocode.github.io/london/faq)
5. [TEAM](https://womenwhocode.github.io/london/team)

**Comment by RossellaFer** [comment]
Hi, I would like to contribute to the project. Is it ok if I work on this issue?

**Comment by dricazenck** [comment]
@RossellaFer thank you for your contribuition, fell free to include yourself as part of our contributors https://womenwhocode.github.io/london/team by add your[ profile here](https://github.com/WomenWhoCode/london/blob/master/_data/collaborators.yml)
