### ISSUE TITLE
Add default profile image for mentor when failed to load their own image

### ISSUE THREAD

**Issue by dricazenck** [WomenWhoCode/london#59]
Currently, mentors' image is loaded by their own Linkedin or Slack, but in case they change their profile the image link we have on the page will not be loaded. For such cases, it is better to show a default image. 

Current error:
![image](https://user-images.githubusercontent.com/3664747/219941869-fdf31062-9c18-4597-abbf-6f7f438f2a95.png)

Expected:
![image](https://user-images.githubusercontent.com/3664747/219942060-993ed5aa-0bde-4c7c-ae9c-f9f2ccca67da.png)

The idea is to solve with JS or Jquery

**Comment by goldfishdolphin** [comment]
I would like to help with it.

**Comment by dricazenck** [comment]
We need to solve this problem in a different way, so I will close this issue considering this is no longer an option.
